export const operatingRules = `Sos Traela, el agente personal de compras para Paraguay. Respondé en español paraguayo con voseo, de forma breve, cálida y clara. Compra como hablás. Ayudá a elegir y recopilar producto, variante, cantidad y presupuesto. No inventes disponibilidad, datos del pedido, precios finales ni ETA. Los precios de búsqueda son internos y no deben mostrarse al cliente como cotización. Solo un operador confirma un único precio final en guaraníes con producto, envío global, gestión y entrega. Pago por transferencia bancaria después del resumen y antes de realizar la compra. Usá envío global, no importación. Pedí únicamente los datos necesarios. Si te preguntan por un pedido, no supongas su estado. No afirmes que un humano recibió la consulta sin confirmación real del backend. Devolvé reply en texto y handoff=true cuando haga falta cotización, ETA, un estado no disponible o una excepción.`;
export type Turn = { role: string; text: string };
export function approvedReply(message: string, history: Turn[]) {
 const q=message.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 if (/^(hola|buenas|buenos dias|buenas tardes|buenas noches|hey)[!. ]*$/.test(q)) return {reply:'Hola, soy Traela. ¿Qué querés comprar? Podés describirlo, pegar un link o mandarme una foto.'};
 if (/^(gracias|muchas gracias|genial|perfecto|ok|dale)[!. ]*$/.test(q)) return {reply:'Dale. ¿En qué más te puedo ayudar?'};
 if (/como (funciona|compro)|que (es|hace) traela/.test(q)) return {reply:'Contame qué querés comprar o pasame un link o una foto. Te ayudo a encontrar opciones. Después confirmamos un único precio final en guaraníes y la fecha estimada de entrega. Pagás por transferencia y coordinamos la compra y la entrega.'};
 if (/como pago|como se paga|formas? de pago|metodos? de pago|aceptan.*(tarjeta|efectivo)|transferencia/.test(q)) return {reply:'El pago es por transferencia bancaria. Primero confirmamos el resumen de tu compra con el precio final en guaraníes y la entrega estimada. La compra se realiza después del pago.'};
 if (/precio final|que incluye|costos? (extra|adicional)|envio incluido/.test(q)) return {reply:'Confirmamos un solo precio final en guaraníes: incluye el producto, el envío global, nuestra gestión y la entrega. El equipo revisa la cotización antes de que pagues.'};
 if (/consultar mi pedido|estado.*pedido|donde.*pedido|seguimiento|mi pedido|numero de pedido/.test(q)) return {reply:'Para consultar tu pedido necesito su número o el nombre del producto. Este chat todavía no tiene acceso al seguimiento de pedidos. Podés continuar por WhatsApp para que revisemos el estado.',handoff:true};
 if (/cuanto tarda|cuando llega|fecha.*entrega|\beta\b|tiempo.*entrega|plazo.*entrega/.test(q)) return {reply:'La fecha depende del producto y de su origen. El equipo confirma una ventana de entrega junto con tu cotización. ¿Qué producto querés comprar?',handoff:true};
 if (/cotiza|cotizacion|presupuesto final|precio confirmado|confirmar (precio|compra)|comprar (este|ese)|lo quiero|quiero ese/.test(q)) return {reply:'Para preparar la cotización, pasanos el producto o link, la variante (talle, color o modelo) y la cantidad. El equipo confirma el precio final y la entrega por WhatsApp. Todavía no se envió una solicitud al equipo desde este chat.',handoff:true};
 if (/foto|imagen/.test(q) && /^(puedo|como|quiero (mandar|enviar|subir)|tengo una)/.test(q)) return {reply:'Usá el botón + para agregar una imagen o tomar una foto. Si tu celular no abre la cámara, podés adjuntar la foto desde tu galería.'};
 if (/^(quiero comprar algo|buscar un producto|no se que comprar)[.! ]*$/.test(q)) return {reply:'¿Qué estás buscando? Contame qué producto necesitás y, si tenés uno, tu presupuesto.'};
 if (/^tengo un link[.! ]*$/.test(q)) return {reply:'Pegá el link acá. Si ya sabés el modelo, talle, color y cantidad, agregalos también.'};
 if (/^(si|no|inalambricos|negro|blanco|azul|rojo|uno|dos|\d+)[.! ]*$/.test(q) && history.length) return {reply:'Agregá el nombre del producto junto con esa preferencia, así puedo buscar una opción que coincida.'};
 return null;
}
