'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useCallback,useEffect,useRef,useState } from 'react';
import './operator.css';
type Conversation={id:string;title:string;status:string;auto_enabled:boolean;notes?:string;quote_pyg?:number;eta_start?:string;eta_end?:string;updated_at:string};
type Message={id:string;role:string;text:string;created_at:string;payload?:{image?:string;audio?:string;products?:{title:string;image_url?:string}[]}};
const labels:Record<string,string>={auto:'Traela responde',needs_quote:'Necesita atención',waiting_payment:'Espera de pago',in_progress:'En curso',closed:'Cerrada'};
const demoConversation:Conversation={id:'00000000-0000-4000-8000-000000000001',title:'Ejemplo · Nike Pegasus 41',status:'needs_quote',auto_enabled:false,notes:'Datos de ejemplo. Confirmar talle y cantidad.',updated_at:'2026-10-08T22:00:00Z'};
const demoMessages:Message[]=[{id:'demo-1',role:'user',text:'Busco unas Nike Pegasus 41, talle 42. ¿Me podés cotizar?',created_at:'2026-10-08T22:00:00Z'},{id:'demo-2',role:'assistant',text:'Dale. El equipo revisará el precio final y la entrega. Tu consulta quedó en la bandeja.',created_at:'2026-10-08T22:00:02Z'}];
export default function Operator(){
 const [state,setState]=useState<'loading'|'setup'|'login'|'ready'>('loading'),[inbox,setInbox]=useState<Conversation[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reply,setReply]=useState(''),[price,setPrice]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[notes,setNotes]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[mobileTab,setMobileTab]=useState<'inbox'|'chat'>('inbox'),[quotePreview,setQuotePreview]=useState(false);
 const [preview,setPreview]=useState(false);
 const demo=useRef(false);
 const selectedRef=useRef(''),tail=useRef<HTMLDivElement>(null),hydrated=useRef('');
 const load=useCallback(async()=>{if(demo.current){setState('ready');setInbox([demoConversation]);if(selectedRef.current){setDetail(demoConversation);setMessages(demoMessages);setNotes(demoConversation.notes||'');}return;}try{const r=await fetch('/api/operator/conversations',{cache:'no-store'});if(r.status===503){setState('setup');return;}if(r.status===401){setState('login');return;}const d=await r.json();if(!r.ok)throw new Error(d.message);setState('ready');setInbox(d.conversations);const id=selectedRef.current;if(id){const response=await fetch(`/api/operator/conversations/${id}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.message);if(selectedRef.current!==id)return;setDetail(data.conversation);setMessages(data.messages);if(hydrated.current!==id){setNotes(data.conversation.notes||'');setPrice(data.conversation.quote_pyg?String(data.conversation.quote_pyg):'');setStart(data.conversation.eta_start||'');setEnd(data.conversation.eta_end||'');hydrated.current=id;}}}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar la bandeja.');}},[]);
 useEffect(()=>{const init=setTimeout(()=>{if(new URLSearchParams(window.location.search).get('preview')==='1'){demo.current=true;setPreview(true);selectedRef.current=demoConversation.id;setSelected(demoConversation.id);}void load();},0);const interval=setInterval(()=>void load(),4000);return()=>{clearTimeout(init);clearInterval(interval);};},[load]);
 useEffect(()=>{tail.current?.scrollIntoView({behavior:'smooth'});},[messages.length]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/operator/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.message);setPassword('');await load();}catch(e){setError(e instanceof Error?e.message:'No pudimos iniciar sesión.');}finally{setBusy(false);}}
 async function action(payload:object){if(demo.current){setError('Esta es una vista previa. No se enviaron mensajes ni se guardaron cambios.');return;}if(!selected)return;setBusy(true);setError('');try{const r=await fetch(`/api/operator/conversations/${selected}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message);await load();setReply('');setQuotePreview(false);}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar.');}finally{setBusy(false);}}
 function choose(c:Conversation){selectedRef.current=c.id;setSelected(c.id);setDetail(null);setMessages([]);setReply('');setQuotePreview(false);setMobileTab('chat');void load();}
 const visible=inbox.filter(c=>(filter==='all'||c.status===filter)&&c.title.toLowerCase().includes(search.toLowerCase()));
 if(state!=='ready')return <main className="operator-gate"><Link href="/" className="op-logo">Traela <span>Operator</span></Link>{state==='loading'?<p>Cargando…</p>:state==='setup'?<><h1>Tu consola está preparada.</h1><p>Para activar la bandeja compartida falta conectar la base de datos y configurar tu acceso privado.</p><div className="setup-items"><span>✓ Bandeja y conversaciones</span><span>✓ Respuestas, cotización y ETA</span><span>✓ Pausa de respuestas automáticas</span><span>○ Conexión y usuario operador pendientes</span></div><p className="setup-note">Hasta activar la conexión, los chats siguen guardándose solo en el navegador de cada cliente. Esta pantalla no muestra conversaciones reales.</p><Link href="/operator?preview=1">Ver la consola con datos de ejemplo →</Link><Link href="/chat">Volver al chat →</Link></>:<><h1>Entrá a tu consola.</h1><p>Acceso privado para el operador de Traela.</p><form onSubmit={login}><label>Email<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'Ingresando…':'Ingresar'}</button></form></>}{error&&<p role="alert" className="op-error">{error}</p>}</main>;
 return <main className="operator-console"><header className="op-header"><Link href="/" className="op-logo">Traela <span>Operator</span></Link><span className="op-live">{preview?'VISTA PREVIA · Datos de ejemplo · No envía mensajes':'● Actualiza cada 4 segundos'}</span><button disabled={preview} onClick={async()=>{await fetch('/api/operator/logout',{method:'POST'});setInbox([]);setMessages([]);setDetail(null);setState('login');}}>Salir</button></header>{error&&<p role="alert" className="op-error">{error}</p>}<div className="op-layout">
 <aside className={`op-inbox ${mobileTab==='chat'?'mobile-hidden':''}`}><div className="inbox-heading"><h1>Conversaciones</h1><span>{inbox.length}</span></div><input aria-label="Buscar conversación" placeholder="Buscar conversación…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar estado" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas las conversaciones</option>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><div className="inbox-list">{visible.map(c=><button className={`inbox-row ${selected===c.id?'selected':''}`} onClick={()=>choose(c)} key={c.id}><span className={`status-dot ${c.status}`}/><div><strong>{c.title}</strong><span>{labels[c.status]}</span></div><time>{new Date(c.updated_at).toLocaleDateString('es-PY',{day:'numeric',month:'short'})}</time></button>)}{!visible.length&&<p className="op-empty">Todavía no hay conversaciones en esta vista.</p>}</div></aside>
 <section className={`op-thread ${mobileTab==='inbox'?'mobile-hidden':''}`}>{!detail?<div className="op-empty-state"><h2>{selected?'Cargando conversación…':'Tu bandeja, en un solo lugar.'}</h2><p>Elegí una conversación para responder o preparar una cotización.</p></div>:<><header className="thread-header"><button className="mobile-back" onClick={()=>setMobileTab('inbox')}>← Bandeja</button><div><h2>{detail.title}</h2><p>{labels[detail.status]} · {detail.id.slice(0,8)}</p></div><button disabled={busy||preview} className={detail.auto_enabled?'auto-on':'auto-off'} onClick={()=>void action({action:'update',auto_enabled:!detail.auto_enabled})}>{detail.auto_enabled?'Pausar Traela':'Reanudar Traela'}</button></header><div className="thread-messages" role="log" aria-label="Mensajes de la conversación">{messages.map(m=><article className={`op-message ${m.role}`} key={m.id}><div><strong>{m.role==='user'?'Cliente':m.role==='operator'?'Vos · Operador':'Traela'}</strong><time>{new Date(m.created_at).toLocaleTimeString('es-PY',{hour:'2-digit',minute:'2-digit'})}</time></div>{m.payload?.image&&<Image unoptimized src={m.payload.image} alt="Imagen del cliente" width={300} height={250}/>} {m.payload?.audio&&<audio src={m.payload.audio} controls/>}<p>{m.text}</p>{m.payload?.products?.map((p,i)=><div className="op-product" key={i}>{p.image_url&&<Image unoptimized src={p.image_url} alt={p.title} width={60} height={60}/>}<span>{p.title}</span></div>)}</article>)}<div ref={tail}/></div><form className="operator-reply" onSubmit={e=>{e.preventDefault();void action({action:'reply',text:reply});}}><textarea aria-label="Respuesta al cliente" placeholder="Escribí tu respuesta al cliente…" value={reply} onChange={e=>setReply(e.target.value)} maxLength={4000}/><div><span>Al responder, Traela queda en pausa.</span><button disabled={busy||preview||!reply.trim()}>Enviar respuesta</button></div></form></>}</section>
 {detail&&<aside className="op-details"><h3>Gestionar conversación</h3><label>Estado<select value={detail.status} disabled={busy||preview} onChange={e=>void action({action:'update',status:e.target.value})}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><form onSubmit={e=>{e.preventDefault();setQuotePreview(true);}}><h3>Cotización y ETA</h3><label>Precio final · ₲<input type="number" min="1" max="1000000000" step="1" required value={price} onChange={e=>{setPrice(e.target.value);setQuotePreview(false);}}/></label><label>Entrega desde<input type="date" required value={start} min={new Date().toISOString().slice(0,10)} onChange={e=>{setStart(e.target.value);setQuotePreview(false);}}/></label><label>Entrega hasta<input type="date" required value={end} min={start||new Date().toISOString().slice(0,10)} onChange={e=>{setEnd(e.target.value);setQuotePreview(false);}}/></label><button disabled={busy}>Revisar cotización</button></form>{quotePreview&&<div className="quote-preview"><strong>₲{new Intl.NumberFormat('es-PY').format(Number(price))}</strong><p>Entrega: {start} al {end}</p><p>Al enviar, el cliente recibirá el precio final y ETA. El estado pasará a espera de pago.</p><button disabled={busy||preview} onClick={()=>void action({action:'quote',price:Number(price),start,end})}>Enviar cotización al cliente</button></div>}<label>Notas internas<textarea value={notes} maxLength={6000} onChange={e=>setNotes(e.target.value)} placeholder="Solo visibles para vos"/></label><button disabled={busy||preview} className="secondary" onClick={()=>void action({action:'update',notes})}>Guardar notas</button></aside>}
 </div></main>;
}
